version: "3"
services:
  app:
    image: app
    ports:
      - "8080:8080"
    depends_on:
          - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ood
      - POSTGRES_PASSWORD=ood
      - POSTGRES_DB=ood

